# AI Image Generation Models Configuration
# Each model has its own optimal settings for maximum quality

models:
  flux:
    class: FluxModel
    enabled: true
    display_name: "FLUX.1-dev"
    model_path_priority:  # Check in order
      - "/home/user/.cache/huggingface/hub/models--black-forest-labs--FLUX.1-dev/snapshots/0ef5fff789c832c5c7f4e127f94c8b54bbcced44"
      - "/home/user/.cache/huggingface/hub/models--black-forest-labs--FLUX.1-dev"
      - "black-forest-labs/FLUX.1-dev"  # Fallback to download
    
    generation:
      dimensions: [1920, 1088]  # Must be divisible by 16
      scheduler: FlowMatchEulerDiscreteScheduler  # REQUIRED for FLUX
      torch_dtype: bfloat16
      steps_range: [95, 100]  # For random selection
      guidance_range: [3.0, 4.0]
      max_sequence_length: 512
      
    pipeline:
      type: "flux_3stage"  # generate→8K→4K
      save_intermediates: false  # Can be overridden per generation
      stage1_resolution: [1920, 1088]
      stage2_upscale: 4  # to 7680x4352
      stage3_downsample: [3840, 2160]
      stages:
        generation:
          resolution: [1920, 1088]
          steps: 100
          guidance: 3.5
        upscale:
          model: "RealESRGAN_x2plus"  # Better for photos
          scale: 2  # Will do 2x twice for 4x total
          tile_size: 512  # Smaller tiles for better quality
          fp32: true
        downsample:
          resolution: [3840, 2160]
          method: "lanczos"
      
    prompt_requirements:
      max_words: 65
      style: "photorealistic_technical"
      prompter: "deepseek"
    
    memory:
      enable_cpu_offload: true
      attention_slicing: 1
      vae_tiling: true
      clear_cache_after: true

  dalle3:
    class: DalleModel
    enabled: true
    display_name: "DALL-E 3"
    api_endpoint: "https://api.openai.com/v1/images/generations"
    
    generation:
      dimensions: [1792, 1024]
      quality: "hd"
      style: "vivid"
      timeout: 60
      
    pipeline:
      type: "dalle_crop_upscale"
      crop_to_16_9: true
      crop_pixels: [80, 80]  # top, bottom
      upscale_factor: 4
      final_resolution: [3840, 2160]
      
    prompt_requirements:
      max_words: 75
      style: "concrete_visual"
      prompter: "deepseek"
      
  gpt_image_1:
    class: GptImageModel
    enabled: true
    display_name: "GPT-Image-1"
    
    variants:
      direct_api:
        endpoint: "https://api.openai.com/v1/images/generations"
        model: "gpt-image-1"
        timeout: 180
      responses_api:
        endpoint: "https://api.openai.com/v1/chat/completions"
        model: "gpt-4o"
        tool: "image_generation"
        
    generation:
      dimensions: [1536, 1024]
      quality: "high"
      
    pipeline:
      type: "gpt_crop_upscale"
      crop_to_16_9: true
      crop_pixels: [80, 80]
      upscale_factor: 4
      final_resolution: [3840, 2160]
      
    prompt_requirements:
      max_words: 80
      style: "descriptive_artistic"
      prompter: "gpt4o"  # For responses_api variant

  sdxl:
    class: SdxlModel
    enabled: true
    display_name: "SDXL Ultimate Photorealistic"
    model_path: "stabilityai/stable-diffusion-xl-base-1.0"  # Fallback
    checkpoint_path: "/home/user/ai-wallpaper/models/checkpoints/Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors"  # Primary - Juggernaut XL
    refiner_model_path: "stabilityai/stable-diffusion-xl-refiner-1.0"  # Fallback
    refiner_checkpoint_path: "/home/user/ai-wallpaper/models/sdxl-refiner/sd_xl_refiner_1.0.safetensors"  # Primary
    
    generation:
      dimensions: [1344, 768]  # Native SDXL 16:9 - will be used in pipeline
      scheduler_options:  # Prioritized for maximum quality
        - HeunDiscreteScheduler         # Best for high-detail, quality-focused
        - KDPM2DiscreteScheduler        # DPM++ 2M equivalent, excellent quality
        - DPMSolverMultistepScheduler   # Good balance of speed and quality
      scheduler_kwargs:
        use_karras_sigmas: true  # Improves quality and prevents artifacts
      torch_dtype: float16
      steps_range: [70, 100]     # Maximum quality range (80 default)
      guidance_range: [7.0, 9.0]  # Photorealistic optimal range (8.0 default)
      
    pipeline:
      type: "sdxl_ultimate"  # Multi-stage progressive upscaling
      stages:
        # Stage 1: Base generation with ensemble of expert denoisers
        base_generation:
          enable_refiner: true
          refiner_switch_at: 0.8  # Base: steps 1-80, Refiner: 81-100
          
        # Stage 2: Initial refinement pass
        initial_refinement:
          enabled: true
          denoising_strength: 0.35
          steps: 50
          use_refiner_model: true
          
        # Stage 3: Progressive upscaling
        progressive_upscale:
          # First upscale: 1.5x to 2016x1152
          stage1:
            scale: 1.5
            denoising_strength: 0.25
            steps: 40
            use_base_model: true
          # Second upscale: 1.5x to 3024x1728  
          stage2:
            scale: 1.5
            denoising_strength: 0.20
            steps: 30
            use_refiner_model: true
            
        # Stage 4: Real-ESRGAN enhancement
        realesrgan:
          scale: 2  # Using x2plus for photos
          model: "RealESRGAN_x2plus"  # Better for photorealistic
          tile_size: 512
          tile_padding: 32
          use_fp32: true  # Maximum precision
          
        # Stage 5: Final processing
        final_processing:
          target_resolution: [3840, 2160]
          downsampling_method: "lanczos"  # Highest quality
          
      # Optional multi-pass refinement (can be enabled for extreme quality)
      multi_pass_refinement:
        enabled: true  # Set to true for absolute maximum quality
        passes:
          - denoising: 0.4
            steps: 30
          - denoising: 0.25
            steps: 20
          - denoising: 0.15
            steps: 15
      
    lora:
      enabled: true
      auto_select_by_theme: true
      max_count: 5  # Maximum simultaneous LoRAs
      weight_sum_max: 4.0  # Total weight limit
      available_loras:
        detail_tweaker_xl:
          path: "/home/user/ai-wallpaper/models/loras/detail/detail_tweaker_xl.safetensors"
          weight_range: [0.8, 1.5]
          categories: ["all"]
          purpose: "Primary detail enhancement"
        better_picture_more_details:
          path: "/home/user/ai-wallpaper/models/loras/detail/better_picture_more_details.safetensors"
          weight_range: [0.6, 1.0]
          categories: ["all"]
          purpose: "Eye, skin, hair detail"
        skin_realism_sdxl:
          path: "/home/user/ai-wallpaper/models/loras/photorealism/skin_realism_sdxl.safetensors"
          weight_range: [0.5, 0.8]
          categories: ["LOCAL_MEDIA", "GENRE_FUSION"]
          purpose: "Natural skin imperfections"
        sdxl_film_photography:
          path: "/home/user/ai-wallpaper/models/loras/effects/sdxl_film_photography.safetensors"
          weight_range: [0.3, 0.6]
          categories: ["ATMOSPHERIC", "SPACE_COSMIC", "TEMPORAL"]
          purpose: "Film grain and cinematic look"
          
    prompt_requirements:
      max_words: 100
      style: "photorealistic_detailed"
      prompter: "deepseek"
      add_photorealistic_prefix: true
      negative_prompt: |
        watercolor, painting, illustration, drawing, sketch, cartoon, anime,
        artistic, painted, brush strokes, canvas texture, paper texture,
        impressionism, expressionism, abstract, stylized,
        oil painting, acrylic, pastel, charcoal,
        (worst quality:1.4), (bad quality:1.4), (poor quality:1.4),
        blurry, soft focus, out of focus, bokeh,
        low resolution, low detail, pixelated, aliasing,
        jpeg artifacts, compression artifacts,
        oversaturated, undersaturated, overexposed, underexposed,
        grainy, noisy, film grain, sensor noise,
        bad anatomy, deformed, mutated, disfigured,
        extra limbs, missing limbs, floating limbs,
        bad hands, missing fingers, extra fingers,
        bad eyes, missing eyes, extra eyes,
        low quality skin, plastic skin, doll skin,
        bad teeth, ugly
      
# Random model selection configuration
random_selection:
  enabled: true
  model_weights:
    flux: 35
    dalle3: 10
    gpt_image_1: 5
    sdxl: 50
    
  # Prevent invalid combinations
  exclusions:
    - model: "flux"
      scheduler: "!FlowMatchEulerDiscreteScheduler"
      
  parameter_randomization:
    steps: "range"  # Use model's steps_range
    guidance: "range"  # Use model's guidance_range
    scheduler: "choice"  # Pick from scheduler_options
    lora_weight: "range"  # Use LoRA's weight_range

# Quality settings (always maximum)
quality:
  always_maximum: true
  jpeg_quality: 100
  png_compression: 0  # No compression
  save_lossless: true
  
# API keys (loaded from environment)
api_keys:
  openai: "${OPENAI_API_KEY}"