# AI Image Generation Models Configuration
# Each model has its own optimal settings for maximum quality

models:
  flux:
    class: FluxModel
    enabled: true
    display_name: "FLUX.1-dev"
    model_path_priority:  # Check in order
      - "/home/user/.cache/huggingface/hub/models--black-forest-labs--FLUX.1-dev/snapshots/0ef5fff789c832c5c7f4e127f94c8b54bbcced44"
      - "/home/user/.cache/huggingface/hub/models--black-forest-labs--FLUX.1-dev"
      - "black-forest-labs/FLUX.1-dev"  # Fallback to download
    
    generation:
      dimensions: [1920, 1088]  # Must be divisible by 16
      scheduler: FlowMatchEulerDiscreteScheduler  # REQUIRED for FLUX
      torch_dtype: bfloat16
      steps_range: [50, 100]  # For random selection
      guidance_range: [2.0, 4.0]
      max_sequence_length: 512
      
    pipeline:
      type: "flux_3stage"  # generate→8K→4K
      save_intermediates: false  # Can be overridden per generation
      stage1_resolution: [1920, 1088]
      stage2_upscale: 4  # to 7680x4352
      stage3_downsample: [3840, 2160]
      stages:
        generation:
          resolution: [1920, 1088]
          steps: 100
          guidance: 3.5
        upscale:
          model: "RealESRGAN_x4plus"
          scale: 4
          tile_size: 1024
          fp32: true
        downsample:
          resolution: [3840, 2160]
          method: "lanczos"
      
    prompt_requirements:
      max_words: 65
      style: "photorealistic_technical"
      prompter: "deepseek"
    
    memory:
      enable_cpu_offload: true
      attention_slicing: 1
      vae_tiling: true
      clear_cache_after: true

  dalle3:
    class: DalleModel
    enabled: true
    display_name: "DALL-E 3"
    api_endpoint: "https://api.openai.com/v1/images/generations"
    
    generation:
      dimensions: [1792, 1024]
      quality: "hd"
      style: "vivid"
      timeout: 60
      
    pipeline:
      type: "dalle_crop_upscale"
      crop_to_16_9: true
      crop_pixels: [80, 80]  # top, bottom
      upscale_factor: 4
      final_resolution: [3840, 2160]
      
    prompt_requirements:
      max_words: 75
      style: "concrete_visual"
      prompter: "deepseek"
      
  gpt_image_1:
    class: GptImageModel
    enabled: true
    display_name: "GPT-Image-1"
    
    variants:
      direct_api:
        endpoint: "https://api.openai.com/v1/images/generations"
        model: "gpt-image-1"
        timeout: 180
      responses_api:
        endpoint: "https://api.openai.com/v1/chat/completions"
        model: "gpt-4o"
        tool: "image_generation"
        
    generation:
      dimensions: [1536, 1024]
      quality: "high"
      
    pipeline:
      type: "gpt_crop_upscale"
      crop_to_16_9: true
      crop_pixels: [80, 80]
      upscale_factor: 4
      final_resolution: [3840, 2160]
      
    prompt_requirements:
      max_words: 80
      style: "descriptive_artistic"
      prompter: "gpt4o"  # For responses_api variant

  sdxl:
    class: SdxlModel
    enabled: true
    display_name: "SDXL + LoRA"
    model_path: "stabilityai/stable-diffusion-xl-base-1.0"
    
    generation:
      dimensions: [1920, 1024]  # Corrected from plan
      scheduler_options:  # For random selection
        - DPMSolverMultistepScheduler
        - EulerAncestralDiscreteScheduler
        - DDIMScheduler
      torch_dtype: float16
      steps_range: [30, 75]
      guidance_range: [5.0, 12.0]
      
    pipeline:
      type: "sdxl_2x"  # Simple 2x upscale to 4K
      upscale_factor: 2
      final_resolution: [3840, 2048]  # Will be cropped to 3840x2160
      enable_img2img_refine: true
      refine_strength_range: [0.2, 0.4]
      
    lora:
      enabled: true
      auto_select_by_theme: true
      available_loras:
        photorealism:
          path: "/home/user/ai-wallpaper/loras/photorealism.safetensors"
          weight_range: [0.6, 0.9]
          categories: ["LOCAL_MEDIA", "NATURE_EXPANDED", "URBAN_CITYSCAPE"]
        anime:
          path: "/home/user/ai-wallpaper/loras/anime.safetensors"
          weight_range: [0.7, 1.0]
          categories: ["ANIME_MANGA", "GENRE_FUSION"]
        architectural:
          path: "/home/user/ai-wallpaper/loras/architectural.safetensors"
          weight_range: [0.5, 0.8]
          categories: ["ARCHITECTURAL", "URBAN_CITYSCAPE"]
          
    prompt_requirements:
      max_words: 100
      style: "detailed_artistic"
      prompter: "deepseek"
      
# Random model selection configuration
random_selection:
  enabled: true
  model_weights:
    flux: 35
    dalle3: 25
    gpt_image_1: 25
    sdxl: 15
    
  # Prevent invalid combinations
  exclusions:
    - model: "flux"
      scheduler: "!FlowMatchEulerDiscreteScheduler"
      
  parameter_randomization:
    steps: "range"  # Use model's steps_range
    guidance: "range"  # Use model's guidance_range
    scheduler: "choice"  # Pick from scheduler_options
    lora_weight: "range"  # Use LoRA's weight_range

# Quality settings (always maximum)
quality:
  always_maximum: true
  jpeg_quality: 100
  png_compression: 0  # No compression
  save_lossless: true
  
# API keys (loaded from environment)
api_keys:
  openai: "${OPENAI_API_KEY}"
  anthropic: "${ANTHROPIC_API_KEY}"  # For future use