# AI Wallpaper System Paths Configuration
# All paths are absolute to avoid any confusion

# Base directories
project_root: ~/ai-wallpaper
logs_dir: ~/ai-wallpaper/logs
images_dir: ~/ai-wallpaper/images
cache_dir: ~/ai-wallpaper/.cache

# History and tracking files
prompt_history: ~/ai-wallpaper/prompt_history.txt
last_run_file: ~/ai-wallpaper/last_run.txt

# Theme database
theme_database: ~/ai-wallpaper/themes_database.txt

# Weather cache
weather_cache_dir: ~/ai-wallpaper/.weather_cache

# Model paths
models:
  flux:
    primary_paths:
      - ${HF_HOME:-~/.cache/huggingface}/hub/models--black-forest-labs--FLUX.1-dev/snapshots/0ef5fff789c832c5c7f4e127f94c8b54bbcced44
      - ${HF_HOME:-~/.cache/huggingface}/hub/models--black-forest-labs--FLUX.1-dev
      - ~/Pictures/ai/models/flux
  
  # Real-ESRGAN paths
  real_esrgan:
    - ${AI_WALLPAPER_ROOT:-~/ai-wallpaper}/Real-ESRGAN/inference_realesrgan.py
    - ~/Real-ESRGAN/inference_realesrgan.py

# Python environments (for potential future use)
python_env: ${AI_WALLPAPER_VENV:-~/.venv}/bin/python3

# Temporary directories
temp_dir: /tmp

# Default output paths
default_output:
  stage1: ${TMPDIR:-/tmp}/flux_stage1.png
  stage2: ${TMPDIR:-/tmp}/flux_stage2.png
  final: ${TMPDIR:-/tmp}/flux_final.png
  wallpaper: ~/Pictures/ai-wallpaper.png